Spec for spender/expenses POST
fylein/fyle-platform-docs pull request #128
Opened 2022-02-16 12:35 UTC by kartikeyrajvaidya

2022-02-16 17:45 UTC, viiicky commented on src/components/schemas/expense.yaml
> +        signifies when this expense was made.
or start as `It signifies...`

2022-02-16 17:45 UTC, viiicky commented on src/components/schemas/expense.yaml
> +        if its a thrid party app, it prefixed with TPA_.
i capital in if

2022-02-16 17:46 UTC, viiicky commented on src/components/schemas/expense.yaml
> +        String denoting the name of the vendor to which the Expense was made.
can consider expense instead of Expense

2022-02-16 17:47 UTC, viiicky commented on src/components/schemas/expense.yaml
> +      description: This fields marks whether a given expense is billable a not.
fields -> field

2022-02-16 17:48 UTC, viiicky commented on src/components/schemas/expense.yaml
> +      description: This fields marks whether a given expense is reimbursable a not.
fields -> field

2022-02-16 17:49 UTC, viiicky commented on src/components/schemas/expense.yaml
> +        This field is applicable only for `Flight`, `Train`, `Bus`, `Taxi` category.
can you confirm if it's true for `Taxi` category also. Asking cause I recently checked the definition of sync function while working on policy doc, and I remember only three categories being handled - flight, train and bus

2022-02-16 17:50 UTC, viiicky commented on src/components/schemas/expense.yaml
> +        index 0 holds onward journey class, index 1 holds return journey travel class.
Start with capital I

2022-02-16 17:50 UTC, viiicky commented on src/components/schemas/expense.yaml
> +        index 0 holds onward journey class, index 1 holds return journey travel class.
either make `journey class` at both the places or make `journey travel class` at both the places

2022-02-16 17:51 UTC, viiicky commented on src/components/schemas/expense.yaml
> +        This field is applicable for only `Hotel` category.
for only -> only for

2022-02-16 17:52 UTC, viiicky commented on src/components/schemas/expense.yaml
> +        For travel between Place A to Place B, this array will contain two items, From location at array index 0 and To location at array index 1.
items, -> items.

2022-02-16 17:52 UTC, viiicky commented on src/components/schemas/expense.yaml
> +        For travel between Place A to Place c and stopping at Place B, this
incomplete sentence

2022-02-16 17:52 UTC, viiicky commented on src/components/schemas/expense.yaml
> +      maxItems: 10
dont know about this; do we restrict to 10 locations?

2022-02-16 17:55 UTC, viiicky commented on reference/spender.yaml
> +    timestamptz_pst:
all the same comments in this green diff section as below

2022-02-16 17:55 UTC, viiicky requested changes
added comments

2022-02-22 09:52 UTC, aditya999123 commented on src/components/schemas/fields.yaml
> +    For travel between Place A to Place B, this array will contain two items, From location at array index 0 and To location at array index 1.
index i and to localtion at index i+1

2022-02-22 09:52 UTC, aditya999123 commented on src/components/schemas/fields.yaml
> +    - null
nullable as true, enum should not have null

2022-02-22 09:56 UTC, aditya999123 commented on src/components/schemas/expense.yaml
> +  type: object
add required keys

2022-02-22 09:56 UTC, aditya999123 approved these changes

2022-02-24 04:44 UTC, viiicky commented on reference/spender.yaml
> +        index 0 holds onward journey travel class, index 1 holds return journey
Capital I

2022-02-24 04:46 UTC, viiicky commented on reference/spender.yaml
> +          description: Tax amount as setup by your organization.
hmmm, tax_amount is setup by organisation??

2022-02-24 04:48 UTC, viiicky commented on src/components/schemas/fields.yaml
> +  description: This field marks whether a given expense is billable a not.
a -> or
please do a round of self review before raising the PR

2022-02-24 04:48 UTC, viiicky commented on src/components/schemas/fields.yaml
> +  description: This field marks whether a given expense is reimbursable a not.
a -> or
please do a round of self review before raising the PR

2022-02-24 04:50 UTC, viiicky commented on reference/spender.yaml
> +        index 0 holds onward journey travel class, index 1 holds return journey
fix it everywhere applicable

2022-04-04 11:39 UTC, merged